### ISSUE TITLE
Session Year is empty in /127.0.0.1/add_student

### ISSUE THREAD

**Issue by ajinzrathod** [Akash1362000/Django_Student_Management_System#3]
**1.** I am Adding First Student in Database. It has a option named `Session Year`. It is blank. Why?

![Screenshot from 2021-06-11 18-09-14](https://user-images.githubusercontent.com/57681532/121702564-9de5a700-caef-11eb-806c-aef76ced94c8.png)

**2**. Manage Session Year does nothing when saved

**Comment by Akash1362000** [comment]
@ajinzrathod You need to create a session first before adding a student to the database.

**Comment by ajinzrathod** [comment]
It would be great if you had sent some screenshot or some code snippet
